### ISSUE TITLE
Subdomain list format

### ISSUE THREAD

**Issue by tonyarris** [JetP1ane/Affinis#1]
Should the list of existing subdomains exclude the target domain portion of the URL? I.e. should it be:

```
dev.jira
mail.corporate
```

or

```
dev.jira.target.com
mail.corporate.target.com
```
Many thanks, great project

**Comment by JetP1ane** [comment]
@tonyarris Hey Tony, I have found that it is most effective and efficient when including the target root and TLD domains as part of the subdomain input (i.e. dev.jira.target.com, mail.corporate.target.com). Just my experience though, but definitely tinker with it.

Thank you.
